/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApkDownloadInfo {
  'url' : string,
  'diskFile' : ExternalBlob,
  'version' : string,
}
export interface Asset {
  'id' : bigint,
  'purchaseDate' : bigint,
  'supplier' : string,
  'name' : string,
  'type' : string,
  'description' : string,
  'lifespan' : bigint,
  'currency' : string,
  'amountInCurrency' : number,
}
export interface Client {
  'id' : bigint,
  'name' : string,
  'contactPerson' : string,
  'email' : string,
  'address' : string,
  'notes' : string,
  'phone' : string,
}
export interface DailyEntry {
  'id' : bigint,
  'expenseType' : string,
  'relatedClientId' : [] | [bigint],
  'entryType' : string,
  'bankAccount' : string,
  'date' : bigint,
  'description' : string,
  'currency' : string,
  'incomeType' : string,
  'notes' : string,
  'paymentType' : string,
  'relatedOrderId' : [] | [bigint],
  'amount' : number,
  'receiptNumber' : string,
}
export interface Document {
  'id' : bigint,
  'blob' : ExternalBlob,
  'name' : string,
  'size' : bigint,
  'type' : string,
  'description' : string,
  'fileType' : string,
  'author' : string,
  'uploadedAt' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : bigint,
  'status' : string,
  'clientId' : [] | [bigint],
  'dueDate' : bigint,
  'description' : string,
  'deposit' : number,
  'invoiceNumber' : string,
  'remainingBalance' : number,
  'currency' : string,
  'amount' : number,
  'startDate' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAsset' : ActorMethod<[Asset], bigint>,
  'addClient' : ActorMethod<[Client], bigint>,
  'addDailyEntry' : ActorMethod<[DailyEntry], bigint>,
  'addDocument' : ActorMethod<
    [string, ExternalBlob, string, string, string, bigint, string],
    bigint
  >,
  'addOrder' : ActorMethod<[Order], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAsset' : ActorMethod<[bigint], undefined>,
  'deleteClient' : ActorMethod<[bigint], undefined>,
  'deleteDailyEntry' : ActorMethod<[bigint], undefined>,
  'deleteDocument' : ActorMethod<[bigint], undefined>,
  'deleteOrder' : ActorMethod<[bigint], undefined>,
  'getAllAssets' : ActorMethod<[], Array<Asset>>,
  'getAllDailyEntries' : ActorMethod<[], Array<DailyEntry>>,
  'getAllDocuments' : ActorMethod<[], Array<Document>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getApkDownloadInfo' : ActorMethod<[], [] | [ApkDownloadInfo]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientsOrderedById' : ActorMethod<[], Array<Client>>,
  'getClientsOrderedByName' : ActorMethod<[], Array<Client>>,
  'getOrdersByClient' : ActorMethod<[bigint], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateApkDownloadInfo' : ActorMethod<[ApkDownloadInfo], undefined>,
  'updateAsset' : ActorMethod<[bigint, Asset], undefined>,
  'updateClient' : ActorMethod<[bigint, Client], undefined>,
  'updateDailyEntry' : ActorMethod<[bigint, DailyEntry], undefined>,
  'updateDocument' : ActorMethod<[bigint, Document], undefined>,
  'updateOrder' : ActorMethod<[bigint, Order], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];