/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Asset = IDL.Record({
  'id' : IDL.Nat,
  'purchaseDate' : IDL.Int,
  'supplier' : IDL.Text,
  'name' : IDL.Text,
  'type' : IDL.Text,
  'description' : IDL.Text,
  'lifespan' : IDL.Int,
  'currency' : IDL.Text,
  'amountInCurrency' : IDL.Float64,
});
export const Client = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'contactPerson' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const DailyEntry = IDL.Record({
  'id' : IDL.Nat,
  'expenseType' : IDL.Text,
  'relatedClientId' : IDL.Opt(IDL.Nat),
  'entryType' : IDL.Text,
  'bankAccount' : IDL.Text,
  'date' : IDL.Nat,
  'description' : IDL.Text,
  'currency' : IDL.Text,
  'incomeType' : IDL.Text,
  'notes' : IDL.Text,
  'paymentType' : IDL.Text,
  'relatedOrderId' : IDL.Opt(IDL.Nat),
  'amount' : IDL.Float64,
  'receiptNumber' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'clientId' : IDL.Opt(IDL.Nat),
  'dueDate' : IDL.Int,
  'description' : IDL.Text,
  'deposit' : IDL.Float64,
  'invoiceNumber' : IDL.Text,
  'remainingBalance' : IDL.Float64,
  'currency' : IDL.Text,
  'amount' : IDL.Float64,
  'startDate' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Document = IDL.Record({
  'id' : IDL.Nat,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'size' : IDL.Nat,
  'type' : IDL.Text,
  'description' : IDL.Text,
  'fileType' : IDL.Text,
  'author' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const ApkDownloadInfo = IDL.Record({
  'url' : IDL.Text,
  'diskFile' : ExternalBlob,
  'version' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAsset' : IDL.Func([Asset], [IDL.Nat], []),
  'addClient' : IDL.Func([Client], [IDL.Nat], []),
  'addDailyEntry' : IDL.Func([DailyEntry], [IDL.Nat], []),
  'addDocument' : IDL.Func(
      [IDL.Text, ExternalBlob, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addOrder' : IDL.Func([Order], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAsset' : IDL.Func([IDL.Nat], [], []),
  'deleteClient' : IDL.Func([IDL.Nat], [], []),
  'deleteDailyEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteDocument' : IDL.Func([IDL.Nat], [], []),
  'deleteOrder' : IDL.Func([IDL.Nat], [], []),
  'getAllAssets' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
  'getAllDailyEntries' : IDL.Func([], [IDL.Vec(DailyEntry)], ['query']),
  'getAllDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getApkDownloadInfo' : IDL.Func([], [IDL.Opt(ApkDownloadInfo)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientsOrderedById' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getClientsOrderedByName' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getOrdersByClient' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateApkDownloadInfo' : IDL.Func([ApkDownloadInfo], [], []),
  'updateAsset' : IDL.Func([IDL.Nat, Asset], [], []),
  'updateClient' : IDL.Func([IDL.Nat, Client], [], []),
  'updateDailyEntry' : IDL.Func([IDL.Nat, DailyEntry], [], []),
  'updateDocument' : IDL.Func([IDL.Nat, Document], [], []),
  'updateOrder' : IDL.Func([IDL.Nat, Order], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Asset = IDL.Record({
    'id' : IDL.Nat,
    'purchaseDate' : IDL.Int,
    'supplier' : IDL.Text,
    'name' : IDL.Text,
    'type' : IDL.Text,
    'description' : IDL.Text,
    'lifespan' : IDL.Int,
    'currency' : IDL.Text,
    'amountInCurrency' : IDL.Float64,
  });
  const Client = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'contactPerson' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DailyEntry = IDL.Record({
    'id' : IDL.Nat,
    'expenseType' : IDL.Text,
    'relatedClientId' : IDL.Opt(IDL.Nat),
    'entryType' : IDL.Text,
    'bankAccount' : IDL.Text,
    'date' : IDL.Nat,
    'description' : IDL.Text,
    'currency' : IDL.Text,
    'incomeType' : IDL.Text,
    'notes' : IDL.Text,
    'paymentType' : IDL.Text,
    'relatedOrderId' : IDL.Opt(IDL.Nat),
    'amount' : IDL.Float64,
    'receiptNumber' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'clientId' : IDL.Opt(IDL.Nat),
    'dueDate' : IDL.Int,
    'description' : IDL.Text,
    'deposit' : IDL.Float64,
    'invoiceNumber' : IDL.Text,
    'remainingBalance' : IDL.Float64,
    'currency' : IDL.Text,
    'amount' : IDL.Float64,
    'startDate' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Document = IDL.Record({
    'id' : IDL.Nat,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'size' : IDL.Nat,
    'type' : IDL.Text,
    'description' : IDL.Text,
    'fileType' : IDL.Text,
    'author' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const ApkDownloadInfo = IDL.Record({
    'url' : IDL.Text,
    'diskFile' : ExternalBlob,
    'version' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAsset' : IDL.Func([Asset], [IDL.Nat], []),
    'addClient' : IDL.Func([Client], [IDL.Nat], []),
    'addDailyEntry' : IDL.Func([DailyEntry], [IDL.Nat], []),
    'addDocument' : IDL.Func(
        [
          IDL.Text,
          ExternalBlob,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addOrder' : IDL.Func([Order], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAsset' : IDL.Func([IDL.Nat], [], []),
    'deleteClient' : IDL.Func([IDL.Nat], [], []),
    'deleteDailyEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteDocument' : IDL.Func([IDL.Nat], [], []),
    'deleteOrder' : IDL.Func([IDL.Nat], [], []),
    'getAllAssets' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
    'getAllDailyEntries' : IDL.Func([], [IDL.Vec(DailyEntry)], ['query']),
    'getAllDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getApkDownloadInfo' : IDL.Func([], [IDL.Opt(ApkDownloadInfo)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientsOrderedById' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getClientsOrderedByName' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getOrdersByClient' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateApkDownloadInfo' : IDL.Func([ApkDownloadInfo], [], []),
    'updateAsset' : IDL.Func([IDL.Nat, Asset], [], []),
    'updateClient' : IDL.Func([IDL.Nat, Client], [], []),
    'updateDailyEntry' : IDL.Func([IDL.Nat, DailyEntry], [], []),
    'updateDocument' : IDL.Func([IDL.Nat, Document], [], []),
    'updateOrder' : IDL.Func([IDL.Nat, Order], [], []),
  });
};

export const init = ({ IDL }) => { return []; };