/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Asset {
    id: bigint;
    purchaseDate: bigint;
    supplier: string;
    name: string;
    type: string;
    description: string;
    lifespan: bigint;
    currency: string;
    amountInCurrency: number;
}
export interface ApkDownloadInfo {
    url: string;
    diskFile: ExternalBlob;
    version: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Document {
    id: bigint;
    blob: ExternalBlob;
    name: string;
    size: bigint;
    type: string;
    description: string;
    fileType: string;
    author: string;
    uploadedAt: bigint;
}
export interface DailyEntry {
    id: bigint;
    expenseType: string;
    relatedClientId?: bigint;
    entryType: string;
    bankAccount: string;
    date: bigint;
    description: string;
    currency: string;
    incomeType: string;
    notes: string;
    paymentType: string;
    relatedOrderId?: bigint;
    amount: number;
    receiptNumber: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Client {
    id: bigint;
    name: string;
    contactPerson: string;
    email: string;
    address: string;
    notes: string;
    phone: string;
}
export interface Order {
    id: bigint;
    status: string;
    clientId?: bigint;
    dueDate: bigint;
    description: string;
    deposit: number;
    invoiceNumber: string;
    remainingBalance: number;
    currency: string;
    amount: number;
    startDate: bigint;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAsset(asset: Asset): Promise<bigint>;
    addClient(client: Client): Promise<bigint>;
    addDailyEntry(entry: DailyEntry): Promise<bigint>;
    addDocument(name: string, blob: ExternalBlob, description: string, type: string, author: string, size: bigint, fileType: string): Promise<bigint>;
    addOrder(order: Order): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteAsset(id: bigint): Promise<void>;
    deleteClient(id: bigint): Promise<void>;
    deleteDailyEntry(id: bigint): Promise<void>;
    deleteDocument(id: bigint): Promise<void>;
    deleteOrder(id: bigint): Promise<void>;
    getAllAssets(): Promise<Array<Asset>>;
    getAllDailyEntries(): Promise<Array<DailyEntry>>;
    getAllDocuments(): Promise<Array<Document>>;
    getAllOrders(): Promise<Array<Order>>;
    getApkDownloadInfo(): Promise<ApkDownloadInfo | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClientsOrderedById(): Promise<Array<Client>>;
    getClientsOrderedByName(): Promise<Array<Client>>;
    getOrdersByClient(clientId: bigint): Promise<Array<Order>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateApkDownloadInfo(newInfo: ApkDownloadInfo): Promise<void>;
    updateAsset(id: bigint, asset: Asset): Promise<void>;
    updateClient(id: bigint, client: Client): Promise<void>;
    updateDailyEntry(id: bigint, entry: DailyEntry): Promise<void>;
    updateDocument(id: bigint, document: Document): Promise<void>;
    updateOrder(id: bigint, order: Order): Promise<void>;
}
import type { ApkDownloadInfo as _ApkDownloadInfo, DailyEntry as _DailyEntry, Document as _Document, ExternalBlob as _ExternalBlob, Order as _Order, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAsset(arg0: Asset): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAsset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAsset(arg0);
            return result;
        }
    }
    async addClient(arg0: Client): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClient(arg0);
            return result;
        }
    }
    async addDailyEntry(arg0: DailyEntry): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDailyEntry(to_candid_DailyEntry_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDailyEntry(to_candid_DailyEntry_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addDocument(arg0: string, arg1: ExternalBlob, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDocument(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDocument(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addOrder(arg0: Order): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrder(to_candid_Order_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrder(to_candid_Order_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAsset(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAsset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAsset(arg0);
            return result;
        }
    }
    async deleteClient(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async deleteDailyEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDailyEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDailyEntry(arg0);
            return result;
        }
    }
    async deleteDocument(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDocument(arg0);
            return result;
        }
    }
    async deleteOrder(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOrder(arg0);
            return result;
        }
    }
    async getAllAssets(): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssets();
            return result;
        }
    }
    async getAllDailyEntries(): Promise<Array<DailyEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDailyEntries();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDailyEntries();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDocuments(): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDocuments();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDocuments();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApkDownloadInfo(): Promise<ApkDownloadInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getApkDownloadInfo();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApkDownloadInfo();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientsOrderedById(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientsOrderedById();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientsOrderedById();
            return result;
        }
    }
    async getClientsOrderedByName(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientsOrderedByName();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientsOrderedByName();
            return result;
        }
    }
    async getOrdersByClient(arg0: bigint): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByClient(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByClient(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateApkDownloadInfo(arg0: ApkDownloadInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApkDownloadInfo(await to_candid_ApkDownloadInfo_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApkDownloadInfo(await to_candid_ApkDownloadInfo_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAsset(arg0: bigint, arg1: Asset): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAsset(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAsset(arg0, arg1);
            return result;
        }
    }
    async updateClient(arg0: bigint, arg1: Client): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0, arg1);
            return result;
        }
    }
    async updateDailyEntry(arg0: bigint, arg1: DailyEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDailyEntry(arg0, to_candid_DailyEntry_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDailyEntry(arg0, to_candid_DailyEntry_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateDocument(arg0: bigint, arg1: Document): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDocument(arg0, await to_candid_Document_n33(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDocument(arg0, await to_candid_Document_n33(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateOrder(arg0: bigint, arg1: Order): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrder(arg0, to_candid_Order_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrder(arg0, to_candid_Order_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_ApkDownloadInfo_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApkDownloadInfo): Promise<ApkDownloadInfo> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_DailyEntry_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyEntry): DailyEntry {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_Document_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Document): Promise<Document> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Order_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ApkDownloadInfo]): Promise<ApkDownloadInfo | null> {
    return value.length === 0 ? null : await from_candid_ApkDownloadInfo_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    expenseType: string;
    relatedClientId: [] | [bigint];
    entryType: string;
    bankAccount: string;
    date: bigint;
    description: string;
    currency: string;
    incomeType: string;
    notes: string;
    paymentType: string;
    relatedOrderId: [] | [bigint];
    amount: number;
    receiptNumber: string;
}): {
    id: bigint;
    expenseType: string;
    relatedClientId?: bigint;
    entryType: string;
    bankAccount: string;
    date: bigint;
    description: string;
    currency: string;
    incomeType: string;
    notes: string;
    paymentType: string;
    relatedOrderId?: bigint;
    amount: number;
    receiptNumber: string;
} {
    return {
        id: value.id,
        expenseType: value.expenseType,
        relatedClientId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.relatedClientId)),
        entryType: value.entryType,
        bankAccount: value.bankAccount,
        date: value.date,
        description: value.description,
        currency: value.currency,
        incomeType: value.incomeType,
        notes: value.notes,
        paymentType: value.paymentType,
        relatedOrderId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.relatedOrderId)),
        amount: value.amount,
        receiptNumber: value.receiptNumber
    };
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    blob: _ExternalBlob;
    name: string;
    size: bigint;
    type: string;
    description: string;
    fileType: string;
    author: string;
    uploadedAt: bigint;
}): Promise<{
    id: bigint;
    blob: ExternalBlob;
    name: string;
    size: bigint;
    type: string;
    description: string;
    fileType: string;
    author: string;
    uploadedAt: bigint;
}> {
    return {
        id: value.id,
        blob: await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value.blob),
        name: value.name,
        size: value.size,
        type: value.type,
        description: value.description,
        fileType: value.fileType,
        author: value.author,
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    clientId: [] | [bigint];
    dueDate: bigint;
    description: string;
    deposit: number;
    invoiceNumber: string;
    remainingBalance: number;
    currency: string;
    amount: number;
    startDate: bigint;
}): {
    id: bigint;
    status: string;
    clientId?: bigint;
    dueDate: bigint;
    description: string;
    deposit: number;
    invoiceNumber: string;
    remainingBalance: number;
    currency: string;
    amount: number;
    startDate: bigint;
} {
    return {
        id: value.id,
        status: value.status,
        clientId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.clientId)),
        dueDate: value.dueDate,
        description: value.description,
        deposit: value.deposit,
        invoiceNumber: value.invoiceNumber,
        remainingBalance: value.remainingBalance,
        currency: value.currency,
        amount: value.amount,
        startDate: value.startDate
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    diskFile: _ExternalBlob;
    version: string;
}): Promise<{
    url: string;
    diskFile: ExternalBlob;
    version: string;
}> {
    return {
        url: value.url,
        diskFile: await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value.diskFile),
        version: value.version
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DailyEntry>): Array<DailyEntry> {
    return value.map((x)=>from_candid_DailyEntry_n16(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Document>): Promise<Array<Document>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Document_n19(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n23(_uploadFile, _downloadFile, x));
}
async function to_candid_ApkDownloadInfo_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApkDownloadInfo): Promise<_ApkDownloadInfo> {
    return await to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_DailyEntry_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DailyEntry): _DailyEntry {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_Document_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Document): Promise<_Document> {
    return await to_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Order_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Order): _Order {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    clientId?: bigint;
    dueDate: bigint;
    description: string;
    deposit: number;
    invoiceNumber: string;
    remainingBalance: number;
    currency: string;
    amount: number;
    startDate: bigint;
}): {
    id: bigint;
    status: string;
    clientId: [] | [bigint];
    dueDate: bigint;
    description: string;
    deposit: number;
    invoiceNumber: string;
    remainingBalance: number;
    currency: string;
    amount: number;
    startDate: bigint;
} {
    return {
        id: value.id,
        status: value.status,
        clientId: value.clientId ? candid_some(value.clientId) : candid_none(),
        dueDate: value.dueDate,
        description: value.description,
        deposit: value.deposit,
        invoiceNumber: value.invoiceNumber,
        remainingBalance: value.remainingBalance,
        currency: value.currency,
        amount: value.amount,
        startDate: value.startDate
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    diskFile: ExternalBlob;
    version: string;
}): Promise<{
    url: string;
    diskFile: _ExternalBlob;
    version: string;
}> {
    return {
        url: value.url,
        diskFile: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.diskFile),
        version: value.version
    };
}
async function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    blob: ExternalBlob;
    name: string;
    size: bigint;
    type: string;
    description: string;
    fileType: string;
    author: string;
    uploadedAt: bigint;
}): Promise<{
    id: bigint;
    blob: _ExternalBlob;
    name: string;
    size: bigint;
    type: string;
    description: string;
    fileType: string;
    author: string;
    uploadedAt: bigint;
}> {
    return {
        id: value.id,
        blob: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.blob),
        name: value.name,
        size: value.size,
        type: value.type,
        description: value.description,
        fileType: value.fileType,
        author: value.author,
        uploadedAt: value.uploadedAt
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    expenseType: string;
    relatedClientId?: bigint;
    entryType: string;
    bankAccount: string;
    date: bigint;
    description: string;
    currency: string;
    incomeType: string;
    notes: string;
    paymentType: string;
    relatedOrderId?: bigint;
    amount: number;
    receiptNumber: string;
}): {
    id: bigint;
    expenseType: string;
    relatedClientId: [] | [bigint];
    entryType: string;
    bankAccount: string;
    date: bigint;
    description: string;
    currency: string;
    incomeType: string;
    notes: string;
    paymentType: string;
    relatedOrderId: [] | [bigint];
    amount: number;
    receiptNumber: string;
} {
    return {
        id: value.id,
        expenseType: value.expenseType,
        relatedClientId: value.relatedClientId ? candid_some(value.relatedClientId) : candid_none(),
        entryType: value.entryType,
        bankAccount: value.bankAccount,
        date: value.date,
        description: value.description,
        currency: value.currency,
        incomeType: value.incomeType,
        notes: value.notes,
        paymentType: value.paymentType,
        relatedOrderId: value.relatedOrderId ? candid_some(value.relatedOrderId) : candid_none(),
        amount: value.amount,
        receiptNumber: value.receiptNumber
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
